# Scotland and Northern Ireland guides (Oct 2026). Checked against: Family Law (Scotland) Act 1985 (matrimonial
# property, relevant date, s.9 principles, s.13 periodical allowance), Family Law (Scotland) Act 2006 s.28
# (cohabitants, one-year limit), Divorce (Scotland) Act 1976; Matrimonial Causes (Northern Ireland) Order 1978
# (fault-based facts, two-year bar, art. 27 factors). UK-wide: Child Maintenance Service, no tax on maintenance.

TAX = ('Maintenance and tax in the UK', '<strong>Maintenance payments are not taxable</strong> income for the person receiving them and <strong>not deductible</strong> for the person paying. Transfers of assets between spouses on separation have special capital gains tax rules with time limits, so check the timing of any sale or transfer with an adviser.')

def house(extra=''):
    return ('p', 'The two biggest assets in most divorces are the family home and pensions. Pensions built up during the marriage are often the largest asset of all, and they can be shared through a <strong>pension sharing order</strong> rather than traded against the house. ' + extra + 'Trading the house for the pension is a common move that can quietly cost a great deal if the after-tax, after-retirement values are not compared properly. Modeling these trade-offs before you agree to anything is exactly the kind of decision <span class="brand-italic">Your Divorce Angel</span> is built to help you see clearly.')

GUIDES = [
dict(slug='scotland', name='Scotland', template='ohio',
  verified='facts checked vs Family Law (Scotland) Act 1985 (matrimonial property, relevant date, s.9 principles, 3-year limit), Family Law (Scotland) Act 2006 s.28, Divorce (Scotland) Act 1976; Oct 2026',
  desc='How money works in a Scottish divorce: matrimonial property and the relevant date, fair (equal) sharing, the five principles, periodical allowance limits, cohabitants\' claims, child maintenance and timing.',
  about=['Scotland divorce', 'matrimonial property', 'fair sharing', 'Family Law (Scotland) Act 1985'],
  lede='Scotland shares what you built during the marriage, values it on the date you separated, and prefers a clean break over long-term maintenance. Its rules are quite different from England\'s. Here is how Scotland handles the money, in plain language.',
  reviewed='Reviewed against the Family Law (Scotland) Acts 1985 and 2006.',
  intro='A Scottish divorce is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how pensions are shared, whether any support is paid and for how long. Scotland has its own law, separate from England and Wales, and this guide walks through how it works.',
  short='Scotland shares <strong>matrimonial property</strong>: what either of you acquired during the marriage, plus the <strong>family home and its contents</strong> even if bought before. Everything is valued at the <strong>relevant date</strong>, usually when you <strong>stopped living together</strong>. The starting point is <strong>equal sharing</strong>. Gifts and inheritances are excluded. Ongoing maintenance is limited, often to <strong>three years</strong>, because Scotland prefers a <strong>clean break</strong>.',
  sections=[
    ('h2', 'How Scotland divides property'),
    ('p', 'Under the Family Law (Scotland) Act 1985, the court aims for a result that is fair and practicable, usually through a <strong>capital sum</strong> or a <strong>transfer of property</strong> rather than ongoing payments. The first principle is that the net value of the <strong>matrimonial property</strong> should be shared fairly, and fair sharing starts from <strong>equal</strong>.'),
    ('h3', 'What counts as matrimonial property'),
    ('ul', ['Property either of you acquired during the marriage and still owned at the relevant date, whoever\'s name it is in, including pensions built up during the marriage',
            'The <strong>family home and its furniture</strong>, even if bought before the marriage, as long as it was acquired for use as the family home',
            '<strong>Not</strong> included: property owned before the marriage (other than the home), <strong>gifts and inheritances</strong> from third parties, and anything acquired after the relevant date']),
    ('h3', 'The relevant date'),
    ('p', 'Everything is valued at the <strong>relevant date</strong>: the earlier of the day you stopped living together and the date the divorce papers were served. You can stop cohabiting while still under one roof if you lead completely separate lives. Growth in value after that date is generally not shared, which matters a great deal for pensions and investments.'),
    ('callout', 'When it is not 50/50', 'Equal sharing can be changed for <strong>special circumstances</strong>, such as an agreement between you, matrimonial property bought with inherited or gifted money, or property given away before the relevant date. The court also weighs the other principles below.'),
    ('h3', 'The house and the pensions'),
    house('Pensions are valued at the relevant date using the Cash Equivalent Transfer Value, apportioned to the years of the marriage. '),
    ('h2', 'The five principles'),
    ('p', 'Scottish courts decide financial claims using five principles:'),
    ('ul', ['<strong>Fair sharing</strong> of the net value of matrimonial property',
            '<strong>Economic advantage and disadvantage:</strong> compensation for a spouse who gave up paid work for the family, or helped the other\'s career',
            '<strong>Childcare costs:</strong> sharing the economic burden of caring for a child under 16',
            '<strong>Adjustment:</strong> support for a dependent spouse for <strong>up to three years</strong> to adjust to life after divorce',
            '<strong>Serious financial hardship:</strong> a long-stop for a spouse facing serious hardship because of age or illness']),
    ('h2', 'Spousal support'),
    ('p', 'A <strong>periodical allowance</strong> (ongoing maintenance) is ordered only when a capital payment or property transfer would be inappropriate or not enough, and only under the childcare, adjustment or hardship principles. Under the adjustment principle it is limited to <strong>three years</strong>. Long-term maintenance is rare in Scotland.'),
    ('callout',) + TAX,
    ('h3', 'Cohabitants'),
    ('p', 'Unmarried couples do not share property the way spouses do, but a former cohabitant can ask the court for a payment for <strong>economic advantage or disadvantage</strong> under section 28 of the Family Law (Scotland) Act 2006. The claim must be made within <strong>one year</strong> of the day you stopped living together.'),
    ('h2', 'Child maintenance'),
    ('p', 'Child maintenance is usually arranged between parents or through the UK <strong>Child Maintenance Service</strong>, which works out a weekly amount as a percentage of the paying parent\'s gross income, reduced for overnight stays and other children they support. Scottish courts deal with child maintenance mainly where the Service cannot, for example school fees or a child over 19 in education.'),
    ('h2', 'The divorce process'),
    ('p', 'You can divorce in Scotland if either of you is domiciled there, or has been habitually resident there for a year. The grounds are irretrievable breakdown, shown by adultery, behaviour, <strong>one year</strong> of living apart if you both agree, or <strong>two years</strong> without agreement. A simplified (do-it-yourself) procedure is available for separation cases with no children under 16 and no financial claims.'),
  ],
  glance=[('Property division', 'Fair sharing of matrimonial property, starting from equal (1985 Act)'),
          ('Included', 'Acquired during the marriage, plus the family home and contents bought before'),
          ('Excluded', 'Premarital property (other than the home), gifts, inheritances, post-separation property'),
          ('Valuation', 'The relevant date: usually when you stopped living together'),
          ('Ongoing support', 'Limited; often up to 3 years; clean break preferred'),
          ('Cohabitants', 's.28 claim within 1 year of separating'),
          ('Grounds', '1 year apart with consent, 2 years without, or adultery or behaviour')],
  questions=['What is our relevant date, and what was everything worth on that day?',
             'Was the house bought for use as our family home, even if before the marriage?',
             'Can I trace any gift or inheritance, including money put into the house?',
             'What were our pensions worth at the relevant date, for the years of the marriage?',
             'Should we look at a capital sum or pension sharing rather than ongoing maintenance?'],
  faqs=[('How is property divided in a Scottish divorce?', 'The net value of matrimonial property, what either spouse acquired during the marriage plus the family home and its contents, is shared fairly, starting from equal sharing.'),
        ('Are inheritances shared in a Scottish divorce?', 'No. Gifts and inheritances from third parties are not matrimonial property, though money from them used to buy matrimonial property can be a special circumstance.'),
        ('What is the relevant date in Scotland?', 'The earlier of the day the spouses stopped living together and the date the divorce papers were served. Property is valued on that date.'),
        ('How long does spousal maintenance last in Scotland?', 'Usually not long. Scotland prefers a clean break; support to adjust to divorce is limited to three years, and longer support is only for serious hardship.'),
        ('Do cohabitants have rights in Scotland?', 'They can claim a payment for economic advantage or disadvantage under section 28 of the 2006 Act, but must do so within one year of separating.')],
  disclaimer='This guide is general financial information about divorce in Scotland and reflects the Family Law (Scotland) Acts 1985 and 2006 as of the date noted. It is not legal advice, and laws and individual circumstances change. Always consult a Scottish family law solicitor for advice specific to your situation.'),

dict(slug='northern-ireland', name='Northern Ireland', template='ohio',
  verified='facts checked vs Matrimonial Causes (Northern Ireland) Order 1978 (five facts, art. 27 factors, pension sharing), Child Maintenance Service NI; no-fault divorce not adopted as of 2026; Oct 2026',
  desc='How money works in a Northern Ireland divorce: fault-based divorce and separation periods, how courts divide assets and pensions, spousal maintenance and the clean break, child maintenance and timing.',
  about=['Northern Ireland divorce', 'financial remedies', 'spousal maintenance', 'Matrimonial Causes (Northern Ireland) Order 1978'],
  lede='Northern Ireland has not adopted England\'s no-fault divorce: you still need a fault or a period of separation. When it comes to money, courts start from fairness and sharing, much like England. Here is how Northern Ireland handles the money, in plain language.',
  reviewed='Reviewed against the Matrimonial Causes (Northern Ireland) Order 1978.',
  intro='A Northern Ireland divorce is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how pensions are shared, whether maintenance is paid and for how long. This guide walks through how Northern Ireland handles each of those questions.',
  short='Divorce in Northern Ireland is still <strong>fault-based</strong>: adultery, behaviour, desertion, or <strong>two years apart with consent</strong> or <strong>five years without</strong>. On money, there is <strong>no fixed formula</strong>: courts weigh the Article 27 factors, meet <strong>needs</strong> first and then aim for <strong>fair sharing</strong>, and favour a <strong>clean break</strong> where possible. Pensions can be shared. Cohabitants have <strong>no automatic claims</strong>.',
  sections=[
    ('h2', 'How Northern Ireland divides property'),
    ('p', 'Financial claims are decided under the Matrimonial Causes (Northern Ireland) Order 1978. Article 27 sets out the factors: the welfare of any children first, then each spouse\'s income and earning capacity, needs and obligations, the standard of living, ages, the length of the marriage, health, contributions (including looking after the home and family), and in rare cases conduct.'),
    ('p', 'There is no formula and no automatic 50/50 split. Northern Ireland courts follow the same broad approach as England and Wales: <strong>meet both spouses\' needs</strong>, especially for housing and children, then share what was built during the marriage fairly, with equal sharing as a yardstick.'),
    ('h3', 'Assets from before the marriage, gifts and inheritances'),
    ('p', 'Property one spouse brought into the marriage, inherited or received as a gift is more likely to be kept by that spouse, particularly after a shorter marriage and where it was kept separate. But it is not excluded by law: if it is needed to meet the other spouse\'s or the children\'s needs, it can be used.'),
    ('h3', 'The house and the pensions'),
    house('Courts can make pension sharing orders, or offset a pension against other assets, and a pension built up over a long marriage is often shared. '),
    ('h2', 'Spousal maintenance'),
    ('p', 'Courts can order maintenance for a set term or open-ended, and they must consider whether a <strong>clean break</strong> is possible, either straight away or after an adjustment period. Maintenance can be varied if circumstances change and ends on the recipient\'s remarriage.'),
    ('callout',) + TAX,
    ('h3', 'Cohabitants'),
    ('p', 'Unmarried couples in Northern Ireland have <strong>no automatic right</strong> to share each other\'s property or to maintenance when they separate. Claims depend on property law (for example a share in a jointly owned home) and on child support for any children.'),
    ('h2', 'Child maintenance'),
    ('p', 'Child maintenance is arranged between parents or through the <strong>Child Maintenance Service</strong> in Northern Ireland, which calculates a weekly amount as a percentage of the paying parent\'s gross income, reduced for overnight stays and other children they support.'),
    ('h2', 'The divorce process'),
    ('p', 'Northern Ireland has <strong>not adopted no-fault divorce</strong>; reform has been discussed but the fault-based system remains. You must show the marriage has broken down irretrievably by one of five facts: adultery, behaviour, two years\' desertion, <strong>two years\' separation with consent</strong>, or <strong>five years\' separation</strong> without it. You generally cannot start a divorce within two years of the wedding. Either spouse must be domiciled in Northern Ireland or have been habitually resident there for a year. The divorce goes through a decree nisi, then a decree absolute; settle the finances before the decree absolute, because it can affect pension and inheritance rights.'),
  ],
  glance=[('Grounds', 'Fault-based: adultery, behaviour, desertion, 2 years apart with consent, 5 years without'),
          ('Property division', 'No formula; Article 27 factors; needs first, then fair sharing'),
          ('Gifts and inheritances', 'More likely kept, but can be used to meet needs'),
          ('Pensions', 'Pension sharing orders available'),
          ('Spousal maintenance', 'Term or open-ended; clean break considered'),
          ('Cohabitants', 'No automatic claims'),
          ('Child maintenance', 'Child Maintenance Service formula')],
  questions=['Which fact will the divorce rely on, and how does that affect the timeline?',
             'What do each of us need for housing, especially if the children live with one of us?',
             'What are our pensions worth, and should we share them rather than offset them?',
             'Is a clean break possible now, or after a set period of maintenance?',
             'Are the finances settled in a court order before the decree absolute?'],
  faqs=[('Is there no-fault divorce in Northern Ireland?', 'No. As of 2026 Northern Ireland still uses the fault-based system: adultery, behaviour, desertion, two years\' separation with consent or five years\' without.'),
        ('How are assets divided in a Northern Ireland divorce?', 'There is no formula. Courts weigh the Article 27 factors, put children\'s welfare first, meet both spouses\' needs and then aim for fair sharing of what was built during the marriage.'),
        ('Are inheritances shared in a Northern Ireland divorce?', 'They are not excluded by law, but they are more likely to be kept by the spouse who received them unless they are needed to meet the other spouse\'s or children\'s needs.'),
        ('Do cohabitants have rights in Northern Ireland?', 'Not automatically. Unmarried partners have no right to share each other\'s property or to maintenance; claims depend on property law and child support.'),
        ('Is maintenance taxable in the UK?', 'No. Maintenance payments are not taxable for the recipient and not deductible for the payer.')],
  disclaimer='This guide is general financial information about divorce in Northern Ireland and reflects the Matrimonial Causes (Northern Ireland) Order 1978 as of the date noted. It is not legal advice, and laws and individual circumstances change. Always consult a Northern Ireland family law solicitor for advice specific to your situation.'),
]
