# Content for the Canadian province and territory guides (Oct 2026).
# Facts checked against: Manitoba Family Law Hub (gov.mb.ca/familylaw) and The Family Property Act (C.C.S.M. c. F25, ss. 7, 16);
# PLEA Saskatchewan and the Saskatchewan Family Property Act (s. 23 exemptions); nsfamilylaw.ca (Nova Scotia
# Matrimonial Property Act); PLEIS-NB (Marital Property Act); Newfoundland and Labrador Family Law Act (ss. 19-22);
# Prince Edward Island Family Law Act; Educaloi (Quebec family patrimony, parental union); Yukon Family Property
# and Support Act; Northwest Territories and Nunavut Family Law Acts. Federal: Divorce Act, Federal Child Support
# Guidelines, Spousal Support Advisory Guidelines, Income Tax Act treatment of support, CPP credit splitting.

TAX = ('Tax works the opposite way from the US',
       'In Canada, <strong>periodic spousal support</strong> paid under a written agreement or court order is <strong>tax-deductible for the payer and taxable income for the recipient</strong>, the reverse of the current US rule. <strong>Lump-sum</strong> spousal support is neither, and <strong>child support</strong> is never deductible or taxable. To claim the spousal deduction you must also be current on any child support owed.')

def house_pensions(extra=''):
    return ('p', 'The two biggest assets in most separations are the family home and retirement savings. Pensions and RRSPs built up during the relationship usually count even if they are in one person\'s name, and dividing them takes the right paperwork so the transfer is not taxed as a withdrawal. <strong>Canada Pension Plan credits</strong> earned while you lived together can also be split through Service Canada, separately from everything else. ' + extra + 'Trading the house for the retirement savings is a common move that can quietly cost a great deal if the after-tax values are not compared properly. Modeling these trade-offs before you agree to anything is exactly the kind of decision <span class="brand-italic">Your Divorce Angel</span> is built to help you see clearly.')

def timeline(place):
    return [('h2', 'The financial timeline'),
            ('p', 'Two things people consistently underestimate: how long the process takes and how much costs rise once you are running a household alone. A realistic sequence: at separation, write down the date and fix the picture of assets, debts and what each of you brought in; exchange full financial disclosure; negotiate the split and support, often through mediation; settle in a written separation agreement or go to court; and carry out the transfers. A divorce itself needs one year of separation (you can live under the same roof and still be separated), and one of you must have lived in %s for at least a year before applying.' % place)]

def child_support(table, extra=''):
    return [('h2', 'Child support'),
            ('p', 'Child support follows the <strong>Federal Child Support Guidelines</strong>: a <strong>table amount</strong> based on the paying parent\'s income and the number of children, using the <strong>%s</strong>, plus a share of <strong>special or extraordinary expenses</strong> such as childcare, in proportion to income. When each parent has the children at least 40%% of the time, the starting point is the difference between the two table amounts. %s' % (table, extra))]

def disclaimer(place, laws):
    return 'This guide is general financial information about separation and divorce in %s and reflects %s as of the date noted. It is not legal advice, and laws and individual circumstances change. Always consult a licensed %s family lawyer for advice specific to your situation.' % (place, laws, place)

GUIDES = []

# ───────────────────────── MANITOBA ─────────────────────────
GUIDES.append(dict(
    slug='manitoba', name='Manitoba',
    verified='facts checked vs Manitoba Family Property Act (C.C.S.M. c. F25, equal sharing, s.7 gifts/inheritances, s.16 valuation date, 60-day and 3-year limits), Manitoba Family Law Hub, federal Divorce Act, SSAG, Federal Child Support Guidelines; Oct 2026',
    desc='How money works in a Manitoba separation or divorce: equal sharing under The Family Property Act, what is excluded, common-law partners, deadlines, spousal support under the SSAG, child support and the Canadian tax treatment.',
    about=['Manitoba divorce', 'family property division', 'spousal support', 'child support', 'The Family Property Act'],
    lede='Manitoba shares what you built together equally, counts the time you lived together before marriage, and gives common-law partners the same property rights after three years. Here is how Manitoba handles the money, in plain language.',
    reviewed="Reviewed against Manitoba's Family Property Act and the federal Divorce Act.",
    intro='A Manitoba separation is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how pensions are split, whether support is paid and for how long. This guide walks through how Manitoba handles each of those questions so you can plan with a clear head.',
    short='Manitoba gives each partner an <strong>equal share of family property</strong>, no matter whose name it is in. Gifts and inheritances from others are <strong>excluded</strong>. Values are taken on the <strong>date you stopped living together</strong>. <strong>Common-law partners</strong> are covered after three years together or a registered relationship. There are <strong>short deadlines</strong>, as little as 60 days after a divorce.',
    sections=[
        ('h2', 'Two sets of rules'),
        ('p', 'A Manitoba divorce runs on two laws. The <strong>divorce itself and support</strong> for married spouses come under the <strong>federal Divorce Act</strong>. <strong>Property</strong> comes under Manitoba\'s <strong>Family Property Act</strong>, and support for unmarried partners under Manitoba\'s <strong>Family Law Act</strong>.'),
        ('h2', 'How Manitoba divides property'),
        ('p', 'Family property is what either of you acquired while married and living together, plus anything acquired while you lived together just before the marriage. Each of you has a right to an <strong>equal share</strong>, whichever one owns it or wherever it is. Running the household and earning the income are given equal weight.'),
        ('p', 'In practice the court does not split each item. Each of you lists your assets and debts, the totals are compared, and the one with more pays the other an <strong>equalization payment</strong> so you end up even. The court can order an asset transferred to cover it.'),
        ('h3', 'What is left out'),
        ('p', '<strong>Gifts and inheritances</strong> from someone else are excluded, along with the income and growth on them, unless they were meant for both of you or the money was used to buy something the family uses. Property owned before you lived together is generally not shared either, except things bought for the family in contemplation of the marriage.'),
        ('h3', 'Family assets and business assets'),
        ('p', 'Manitoba separates <strong>family assets</strong> (the home, furniture, the family car, a cottage, family savings, RRSPs) from <strong>commercial assets</strong> such as a business or professional practice. A farmhouse and the land around it are a family asset; the rest of the farm may be commercial. Family assets are split unequally only if an equal split would be grossly unfair because of extraordinary circumstances; for commercial assets the test is slightly easier. Unequal splits are rare.'),
        ('h3', 'The valuation date'),
        ('p', 'Unless you agree otherwise, everything is valued on the <strong>date you last lived together</strong>. That date can move numbers a lot when markets or house prices change, so write it down and keep statements from that month.'),
        ('callout', 'Deadlines are short in Manitoba', 'If property has not been dealt with, an ex-spouse has only <strong>60 days after the divorce takes effect</strong> to apply. Registered common-law partners have 60 days after registering the end of the relationship, and unregistered common-law partners have <strong>three years from separation</strong>. Settle property before the divorce is final.'),
        ('h3', 'Common-law partners'),
        ('p', 'The same property rules apply to common-law partners who <strong>registered their relationship</strong> with the Vital Statistics Agency or lived together for <strong>three years</strong>. Partners who do not qualify keep what is in their own name, but can claim for what they contributed to the other\'s property, and share equally in anything owned jointly.'),
        ('h3', 'The house and the pensions'),
        house_pensions('Manitoba\'s Pension Benefits Act also lets a workplace pension earned during the relationship be shared. '),
        ('h2', 'Spousal support'),
        ('p', 'Married spouses claim spousal support under the <strong>Divorce Act</strong>; common-law partners under Manitoba\'s <strong>Family Law Act</strong> after three years together, or one year with a child, or a registered relationship. Courts rely on the <strong>Spousal Support Advisory Guidelines (SSAG)</strong>: advisory, not binding, but the practical starting point, with separate formulas depending on whether child support is also paid.'),
        ('callout',) + TAX,
    ] + child_support('Manitoba table', 'Manitoba\'s <strong>Child Support Service</strong> can make an initial child support decision without going to court, and the Maintenance Enforcement Program can collect payments.') + timeline('Manitoba'),
    glance=[('Property division', 'Equal sharing of family property, settled by an equalization payment (Family Property Act)'),
            ('Excluded', 'Gifts and inheritances from others (and their growth); property owned before living together'),
            ('Valuation date', 'The date you last lived together, unless you agree otherwise'),
            ('Common-law', 'Covered after 3 years together or a registered relationship'),
            ('Deadline', '60 days after a divorce; 3 years after separation for unregistered partners'),
            ('Spousal support', 'SSAG (advisory)'),
            ('Child support', 'Federal Child Support Guidelines (Manitoba table)')],
    questions=['What is our separation date, and what was everything worth on that day?',
               'Which assets are family assets and which are commercial, such as a business or farm land?',
               'Can I trace any gift or inheritance, and was any of it used for family purchases?',
               'Have pensions and CPP credits been valued and included on both sides?',
               'Are we sure property will be settled before the 60-day deadline after the divorce?'],
    faqs=[('How is property divided in a Manitoba divorce?', 'Each spouse has a right to an equal share of family property, acquired while married and living together (and during cohabitation just before the marriage), regardless of whose name it is in. It is usually settled by an equalization payment rather than splitting each item.'),
          ('Are gifts and inheritances shared in Manitoba?', 'Generally no. Gifts and inheritances from a third party, and the income or growth on them, are excluded unless they were meant to benefit both of you or were used to buy a family asset.'),
          ('Do common-law partners get the same property rights in Manitoba?', 'Yes, if they registered their relationship with the Vital Statistics Agency or lived together for three years. Others can still claim for contributions to the other partner\'s property and share in anything jointly owned.'),
          ('Is there a deadline to divide property in Manitoba?', 'Yes. An ex-spouse must apply within 60 days after the divorce takes effect if property has not been dealt with. Unregistered common-law partners have three years from separation.'),
          ('Is spousal support taxable in Canada?', 'Yes. Periodic spousal support paid under a written agreement or court order is taxable to the recipient and deductible for the payer. Lump-sum support is neither, and child support is never taxable or deductible.')],
    disclaimer=disclaimer('Manitoba', "Manitoba's Family Property Act and Family Law Act and the federal Divorce Act"),
))

# ───────────────────────── SASKATCHEWAN ─────────────────────────
GUIDES.append(dict(
    slug='saskatchewan', name='Saskatchewan',
    verified='facts checked vs Saskatchewan Family Property Act (equal division, family home and household goods not exempt, s.23 exemptions at start-of-relationship value, 24-month limit for unmarried spouses), PLEA Saskatchewan, federal Divorce Act, SSAG, Federal Child Support Guidelines; Oct 2026',
    desc='How money works in a Saskatchewan separation or divorce: equal division under The Family Property Act, the special rule for the family home, exemptions, spouses who lived together two years, deadlines, support and the Canadian tax treatment.',
    about=['Saskatchewan divorce', 'family property division', 'family home', 'spousal support', 'The Family Property Act'],
    lede='Saskatchewan splits family property equally, treats the family home as shared even if one of you owned it first, and gives couples who lived together for two years the same rights as married spouses. Here is how Saskatchewan handles the money, in plain language.',
    reviewed="Reviewed against Saskatchewan's Family Property Act and the federal Divorce Act.",
    intro='A Saskatchewan separation is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how pensions are split, whether support is paid and for how long. This guide walks through how Saskatchewan handles each of those questions.',
    short='Saskatchewan presumes an <strong>equal split</strong> of family property. You can keep the <strong>value of what you owned before</strong> the relationship, but <strong>not the family home or household goods</strong>, and growth on what you brought in is usually shared. Couples who <strong>lived together two years</strong> are spouses too. Married spouses must apply <strong>before the divorce</strong>; others within <strong>24 months of separating</strong>.',
    sections=[
        ('h2', 'Two sets of rules'),
        ('p', 'A Saskatchewan divorce runs on two laws. The <strong>divorce itself and support</strong> for married spouses come under the <strong>federal Divorce Act</strong>. <strong>Property</strong> comes under Saskatchewan\'s <strong>Family Property Act</strong>, and support for unmarried spouses under <strong>The Family Maintenance Act, 1997</strong>.'),
        ('h2', 'How Saskatchewan divides property'),
        ('p', 'Each spouse is entitled to an <strong>equal share of family property</strong>, whoever\'s name it is in, because raising children, running the household and earning money all count as contributions. A court can order something other than half if an equal split would be unfair, looking at things like how long you lived together, when and how property was acquired, debts, and tax on a sale. Misconduct in the relationship is generally not considered, but hiding or giving away property is.'),
        ('h3', 'The family home is different'),
        ('p', 'The <strong>family home</strong> is divided equally on its full value unless that would be unfair and unjust, and an uneven split needs <strong>extraordinary circumstances</strong>. Even if you owned the house before your spouse moved in, you usually cannot claim it as exempt. <strong>Household goods</strong> are treated the same way.'),
        ('h3', 'What you brought in'),
        ('p', 'You can claim an <strong>exemption for the value of property you owned before</strong> you became spouses, measured on the date the relationship began. Any <strong>increase in value</strong> since then is generally shared. Exemptions can be traced into new property: cash an exempt investment to buy art and the exemption follows, but use it on a family car (a household good) and it is lost.'),
        ('callout', 'Apply in time', 'Married spouses must apply to divide family property <strong>before they are divorced</strong>. Unmarried spouses must apply <strong>within 24 months</strong> of separating. Missing these can cost you your share.'),
        ('h3', 'Unmarried spouses'),
        ('p', 'Couples who have lived together <strong>as spouses for two years or more</strong> are treated as spouses for property and support. Shorter relationships fall back on general claims such as unjust enrichment.'),
        ('h3', 'The house and the pensions'),
        house_pensions(),
        ('h2', 'Spousal support'),
        ('p', 'There is <strong>no automatic right</strong> to spousal support, but either spouse can ask. Married spouses claim under the <strong>Divorce Act</strong>, unmarried spouses under <strong>The Family Maintenance Act, 1997</strong>. Courts weigh each spouse\'s finances and needs, the length of the relationship and the roles each played, and use the <strong>Spousal Support Advisory Guidelines (SSAG)</strong> as the starting point. They are advisory, not mandatory.'),
        ('callout',) + TAX,
    ] + child_support('Saskatchewan table', 'Saskatchewan\'s Maintenance Enforcement Office can collect payments.') + timeline('Saskatchewan'),
    glance=[('Property division', 'Presumed equal split of family property (Family Property Act)'),
            ('Family home', 'Shared on full value, even if one spouse owned it first'),
            ('Exemptions', 'Value of property owned before the relationship; growth usually shared'),
            ('Who is a spouse', 'Married, or lived together as spouses for 2 years or more'),
            ('Deadline', 'Before the divorce (married); within 24 months of separation (unmarried)'),
            ('Spousal support', 'SSAG (advisory)'),
            ('Child support', 'Federal Child Support Guidelines (Saskatchewan table)')],
    questions=['What was each of us worth on the day the relationship began, and can we prove it?',
               'Is the house we live in the family home, and was any part of it owned before?',
               'How much has property we brought in grown, since that growth is usually shared?',
               'Have pensions and CPP credits been valued and included on both sides?',
               'Have we applied to divide property before the divorce, or within 24 months if we were not married?'],
    faqs=[('How is property divided in a Saskatchewan divorce?', 'Each spouse is entitled to an equal share of family property, regardless of whose name it is in. A court can order a different split if equal division would be unfair.'),
          ('Is the family home shared if I owned it before we got together?', 'Usually yes. The family home and household goods generally cannot be claimed as exempt, so the full value is presumed to be shared equally unless that would be unfair and unjust.'),
          ('Do common-law couples have property rights in Saskatchewan?', 'Yes, if they lived together as spouses for two years or more. They must apply within 24 months of separating.'),
          ('Is there a deadline to divide property in Saskatchewan?', 'Married spouses must apply before they are divorced. Unmarried spouses must apply within 24 months after separation.'),
          ('Is spousal support taxable in Canada?', 'Yes. Periodic spousal support paid under a written agreement or court order is taxable to the recipient and deductible for the payer. Lump-sum support is neither, and child support is never taxable or deductible.')],
    disclaimer=disclaimer('Saskatchewan', "Saskatchewan's Family Property Act and Family Maintenance Act, 1997 and the federal Divorce Act"),
))

# ───────────────────────── NOVA SCOTIA ─────────────────────────
GUIDES.append(dict(
    slug='nova-scotia', name='Nova Scotia',
    verified='facts checked vs Nova Scotia Matrimonial Property Act (assets owned before or during marriage, exclusions incl. business assets, equal division, registered domestic partners), nsfamilylaw.ca, federal Divorce Act, SSAG, Federal Child Support Guidelines; Oct 2026',
    desc='How money works in a Nova Scotia separation or divorce: equal division of matrimonial assets (including what you owned before marriage), the exclusions, business assets, common-law couples, support and the Canadian tax treatment.',
    about=['Nova Scotia divorce', 'matrimonial property', 'spousal support', 'child support', 'Matrimonial Property Act'],
    lede='Nova Scotia shares matrimonial assets equally, and that can include what you owned before the marriage. Business assets, gifts and inheritances are usually left out, and common-law couples are not covered unless they registered. Here is how Nova Scotia handles the money, in plain language.',
    reviewed="Reviewed against Nova Scotia's Matrimonial Property Act and the federal Divorce Act.",
    intro='A Nova Scotia separation is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how pensions are split, whether support is paid and for how long. This guide walks through how Nova Scotia handles each of those questions.',
    short='Nova Scotia divides <strong>matrimonial assets equally</strong>, and they include property owned <strong>before or during</strong> the marriage. <strong>Gifts, inheritances and business assets</strong> are generally excluded. The law covers <strong>married spouses and registered domestic partners</strong>, not other common-law couples. An unequal split is possible only when 50/50 would be really unfair.',
    sections=[
        ('h2', 'Two sets of rules'),
        ('p', 'A Nova Scotia divorce runs on two laws. The <strong>divorce itself and support</strong> for married spouses come under the <strong>federal Divorce Act</strong>. <strong>Property</strong> comes under Nova Scotia\'s <strong>Matrimonial Property Act</strong>, and support outside a divorce under the <strong>Parenting and Support Act</strong>.'),
        ('h2', 'How Nova Scotia divides property'),
        ('p', 'Matrimonial assets are property owned or obtained by either or both spouses <strong>before or during the marriage</strong>. That covers the home and cottage, household contents, vehicles, pensions (including CPP), RRSPs, savings, investments, tax refunds and severance packages. The starting point is an <strong>equal division</strong>.'),
        ('h3', 'What is excluded'),
        ('ul', ['<strong>Gifts, inheritances and trusts</strong>, unless they were used for the family during the marriage',
                '<strong>Damages awards and insurance proceeds</strong>, unless used for the family',
                '<strong>Business assets</strong>, with some exceptions where the other spouse contributed',
                'Reasonable personal effects such as clothing',
                'Property excluded by a marriage contract or separation agreement, and property acquired after separation']),
        ('p', 'An <strong>unequal split</strong> is considered only where 50/50 would be really unfair: for example a short marriage where one spouse brought most of the property, one spouse wasting assets, or one spouse giving up a career to care for children.'),
        ('callout', 'Owning it before the wedding may not protect it', 'Unlike some provinces, Nova Scotia counts property you owned <strong>before</strong> the marriage as matrimonial. If you want something kept separate, it needs to fall under an exclusion or be dealt with in a marriage contract.'),
        ('h3', 'The matrimonial home'),
        ('p', 'Both spouses have an equal right to live in the home even if only one is on the title, and neither can sell or mortgage it without the other\'s consent. A court can give one spouse <strong>exclusive possession</strong>, looking at the children\'s needs and housing alternatives. Moving out does not give up your share.'),
        ('h3', 'Debts'),
        ('p', 'Debts taken on during the marriage for ordinary family purposes, such as the mortgage, a family car loan or household bills, are matrimonial debts and are usually shared. You are generally not responsible for the other spouse\'s personal debts unless you co-signed.'),
        ('h3', 'Common-law couples'),
        ('p', 'The Matrimonial Property Act applies to <strong>married spouses and registered domestic partners</strong>. Common-law couples who did not register do not get equal division, though they can still split CPP credits after living together for more than a year and may have other claims.'),
        ('h3', 'The house and the pensions'),
        house_pensions('A workplace pension is divided by written agreement or court order, often as a lump sum moved to a locked-in RRSP. '),
        ('h2', 'Spousal support'),
        ('p', 'Married spouses claim spousal support under the <strong>Divorce Act</strong>; others under the <strong>Parenting and Support Act</strong>. Courts rely on the <strong>Spousal Support Advisory Guidelines (SSAG)</strong>: advisory, not binding, but the practical starting point.'),
        ('callout',) + TAX,
    ] + child_support('Nova Scotia table', 'The Maintenance Enforcement Program can collect payments.') + timeline('Nova Scotia'),
    glance=[('Property division', 'Equal division of matrimonial assets (Matrimonial Property Act)'),
            ('Owned before marriage', 'Usually included'),
            ('Excluded', 'Gifts, inheritances, trusts, business assets, personal effects'),
            ('Who is covered', 'Married spouses and registered domestic partners'),
            ('Spousal support', 'SSAG (advisory)'),
            ('Child support', 'Federal Child Support Guidelines (Nova Scotia table)')],
    questions=['Which of our assets are business assets, and did the other spouse contribute to them?',
               'Can I show any gift or inheritance was kept separate and not used for the family?',
               'Would a 50/50 split be really unfair here, for example after a short marriage?',
               'Have pensions and CPP credits been valued and included on both sides?',
               'What does the SSAG range suggest for support, and how does tax change its real value?'],
    faqs=[('How is property divided in a Nova Scotia divorce?', 'Matrimonial assets, property owned or obtained by either spouse before or during the marriage, are divided equally. An unequal division is considered only where 50/50 would be really unfair.'),
          ('Is property I owned before the marriage shared in Nova Scotia?', 'Usually yes. Nova Scotia counts property owned before the marriage as matrimonial unless an exclusion applies, such as a gift, inheritance or business asset.'),
          ('Are business assets divided in Nova Scotia?', 'Business assets are generally excluded from matrimonial assets, with possible exceptions where the other spouse contributed to the business.'),
          ('Does the Matrimonial Property Act cover common-law couples?', 'No. It applies to married spouses and registered domestic partners. Unregistered common-law partners can split CPP credits after more than a year together and may have other claims.'),
          ('Is spousal support taxable in Canada?', 'Yes. Periodic spousal support paid under a written agreement or court order is taxable to the recipient and deductible for the payer. Lump-sum support is neither, and child support is never taxable or deductible.')],
    disclaimer=disclaimer('Nova Scotia', "Nova Scotia's Matrimonial Property Act and Parenting and Support Act and the federal Divorce Act"),
))

# ───────────────────────── NEW BRUNSWICK ─────────────────────────
GUIDES.append(dict(
    slug='new-brunswick', name='New Brunswick',
    verified='facts checked vs New Brunswick Marital Property Act (marital property owned before or during marriage, equal share, business assets excluded, 60 days after divorce), PLEIS-NB, federal Divorce Act, SSAG, Federal Child Support Guidelines; Oct 2026',
    desc='How money works in a New Brunswick separation or divorce: equal shares of marital property under the Marital Property Act, the home and household goods, business assets, the 60-day deadline, support and the Canadian tax treatment.',
    about=['New Brunswick divorce', 'marital property', 'spousal support', 'child support', 'Marital Property Act'],
    lede='New Brunswick gives each spouse an equal share of the property the family used, whether it was bought before or during the marriage. Business assets are treated separately, and the deadline after a divorce is short. Here is how New Brunswick handles the money, in plain language.',
    reviewed="Reviewed against New Brunswick's Marital Property Act and the federal Divorce Act.",
    intro='A New Brunswick separation is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how pensions are split, whether support is paid and for how long. This guide walks through how New Brunswick handles each of those questions.',
    short='Under the Marital Property Act each spouse is entitled to an <strong>equal share of marital property</strong>: what the family used, whether owned <strong>before or during</strong> the marriage. <strong>Business assets</strong> are generally not marital property. Debts are shared too. Apply <strong>before the divorce or within 60 days after</strong>. Common-law couples are not covered unless they signed an agreement.',
    sections=[
        ('h2', 'Two sets of rules'),
        ('p', 'A New Brunswick divorce runs on two laws. The <strong>divorce itself and support</strong> for married spouses come under the <strong>federal Divorce Act</strong>. <strong>Property</strong> comes under New Brunswick\'s <strong>Marital Property Act</strong>, and support outside a divorce under the provincial <strong>Family Law Act</strong>.'),
        ('h2', 'How New Brunswick divides property'),
        ('p', 'Marital property is what the family usually used while you lived together, owned by either or both of you, <strong>before or during the marriage</strong>: the home, a cabin or camper, furniture and appliances, money and investments, cars and recreational vehicles. Each spouse is entitled to an <strong>equal share</strong>, and both have an equal right to stay in the marital home and use household items.'),
        ('h3', 'Debts are shared too'),
        ('p', 'Mortgages, car loans, credit card balances and lines of credit taken on during the relationship are shared, whichever spouse signed for them. A court can relieve a spouse of some debts if that is fair after looking at the whole situation.'),
        ('h3', 'Business assets'),
        ('p', 'Assets used for a <strong>business</strong> are generally not marital property. If one of you owns a business, its value and how it was built up need careful attention, because the court can still look at fairness overall.'),
        ('callout', 'Do not miss the 60-day window', 'An application to divide marital property can be made before the divorce or annulment, or <strong>within 60 days after</strong> it. You do not need to be formally separated to apply if the marriage has broken down.'),
        ('h3', 'Common-law couples'),
        ('p', 'The Marital Property Act is for married spouses. Unmarried couples are covered only if they signed a cohabitation agreement or similar contract that sets out how property is divided; otherwise each keeps what is in their name, subject to claims such as unjust enrichment.'),
        ('h3', 'The house and the pensions'),
        house_pensions(),
        ('h2', 'Spousal support'),
        ('p', 'Married spouses claim spousal support under the <strong>Divorce Act</strong>; unmarried partners who qualify under the provincial <strong>Family Law Act</strong>. Courts rely on the <strong>Spousal Support Advisory Guidelines (SSAG)</strong>: advisory, not binding, but the practical starting point.'),
        ('callout',) + TAX,
    ] + child_support('New Brunswick table', 'The Family Support Orders Service can collect payments.') + timeline('New Brunswick'),
    glance=[('Property division', 'Equal share of marital property (Marital Property Act)'),
            ('Owned before marriage', 'Included if the family used it'),
            ('Business assets', 'Generally not marital property'),
            ('Debts', 'Shared, whichever spouse incurred them during the relationship'),
            ('Deadline', 'Before the divorce or within 60 days after'),
            ('Spousal support', 'SSAG (advisory)'),
            ('Child support', 'Federal Child Support Guidelines (New Brunswick table)')],
    questions=['Which of our assets did the family actually use, and which were used for a business?',
               'Which debts were taken on for the family, and should any be left with one spouse?',
               'Have pensions and CPP credits been valued and included on both sides?',
               'Will property be settled before the divorce, or within 60 days after?',
               'What does the SSAG range suggest for support, and how does tax change its real value?'],
    faqs=[('How is property divided in a New Brunswick divorce?', 'Each spouse is entitled to an equal share of marital property: the property the family usually used, owned by either spouse before or during the marriage. A court can decide otherwise where that is fair.'),
          ('Is a business divided in New Brunswick?', 'Assets used for a business are generally not marital property, though a court looks at fairness overall.'),
          ('Is there a deadline to divide property in New Brunswick?', 'Yes. An application can be made before the divorce or annulment, or within 60 days after it.'),
          ('Do common-law couples share property in New Brunswick?', 'Not under the Marital Property Act, unless they signed an agreement that applies it. Other claims, such as unjust enrichment, may be available.'),
          ('Is spousal support taxable in Canada?', 'Yes. Periodic spousal support paid under a written agreement or court order is taxable to the recipient and deductible for the payer. Lump-sum support is neither, and child support is never taxable or deductible.')],
    disclaimer=disclaimer('New Brunswick', "New Brunswick's Marital Property Act and Family Law Act and the federal Divorce Act"),
))

# ───────────────────────── NEWFOUNDLAND AND LABRADOR ─────────────────────────
GUIDES.append(dict(
    slug='newfoundland-and-labrador', name='Newfoundland and Labrador',
    possessive="Newfoundland and Labrador's",
    verified='facts checked vs Newfoundland and Labrador Family Law Act (RSNL 1990 c. F-2, ss. 19-22: matrimonial home, matrimonial assets, unequal division only if grossly unjust or unconscionable, 2-year limit), federal Divorce Act, SSAG, Federal Child Support Guidelines; Oct 2026',
    desc='How money works in a Newfoundland and Labrador separation or divorce: equal division of matrimonial assets and the matrimonial home under the Family Law Act, exclusions, common-law couples, the two-year deadline, support and tax.',
    about=['Newfoundland and Labrador divorce', 'matrimonial assets', 'matrimonial home', 'spousal support', 'Family Law Act'],
    lede='Newfoundland and Labrador divides matrimonial assets equally and gives each spouse half the matrimonial home, even if it was owned before the wedding. Common-law partners are not covered. Here is how the province handles the money, in plain language.',
    reviewed="Reviewed against Newfoundland and Labrador's Family Law Act and the federal Divorce Act.",
    intro='A separation in Newfoundland and Labrador is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how pensions are split, whether support is paid and for how long. This guide walks through how the province handles each of those questions.',
    short='The Family Law Act presumes an <strong>equal split of matrimonial assets</strong>, whoever\'s name they are in. Each spouse has a <strong>half interest in the matrimonial home</strong>, even one owned before marriage. <strong>Gifts, inheritances and business assets</strong> are usually excluded. Unequal splits need equal division to be <strong>grossly unjust or unconscionable</strong>. <strong>Common-law partners</strong> have no automatic property rights.',
    sections=[
        ('h2', 'Two sets of rules'),
        ('p', 'A divorce here runs on two laws. The <strong>divorce itself and support</strong> for married spouses come under the <strong>federal Divorce Act</strong>. <strong>Property</strong> and support outside a divorce come under the province\'s <strong>Family Law Act</strong>.'),
        ('h2', 'How Newfoundland and Labrador divides property'),
        ('p', 'Matrimonial assets, generally what was acquired during the marriage and used for family purposes (bank accounts, pensions and RRSPs, vehicles, investments, household goods), are presumed to be <strong>split equally</strong>, regardless of whose name is on them. A court departs from that only if an equal split would be <strong>grossly unjust or unconscionable</strong>, which is rare.'),
        ('h3', 'The matrimonial home'),
        ('p', 'Each spouse holds a <strong>50% interest in the matrimonial home</strong> regardless of title, with an equal right to use it, and that applies whether the home was bought <strong>before or during</strong> the marriage. Neither spouse can sell or mortgage it without the other\'s written consent.'),
        ('h3', 'What is usually left out'),
        ('p', 'Gifts from someone else, inheritances, personal injury awards (other than for lost income), family heirlooms and personal items, and <strong>business assets</strong> not used for family purposes are typically excluded. Property from before the marriage can become shared if the family used it. Keeping an inheritance in a separate account matters: mixing it into a joint account can undo the exclusion, and the spouse claiming it has to prove it.'),
        ('callout', 'Two years after the divorce', 'A claim to divide matrimonial assets has to be started within <strong>two years</strong> of the divorce. Do not let it slide once the divorce is granted.'),
        ('h3', 'Common-law couples'),
        ('p', 'The property rules apply only to <strong>married spouses</strong>. Common-law partners keep what is in their own names unless they can prove a claim such as unjust enrichment, or signed a cohabitation agreement that adopts the Act\'s rules.'),
        ('h3', 'The house and the pensions'),
        house_pensions('A workplace pension is valued on what was earned between marriage and separation. '),
        ('h2', 'Spousal support'),
        ('p', 'Married spouses claim spousal support under the <strong>Divorce Act</strong>; others under the provincial <strong>Family Law Act</strong>. Courts rely on the <strong>Spousal Support Advisory Guidelines (SSAG)</strong>: advisory, not binding, but the practical starting point.'),
        ('callout',) + TAX,
    ] + child_support('Newfoundland and Labrador table', 'The Support Enforcement Program can collect payments.') + timeline('Newfoundland and Labrador'),
    glance=[('Property division', 'Presumed equal split of matrimonial assets (Family Law Act)'),
            ('Matrimonial home', '50% each, even if owned before marriage'),
            ('Excluded', 'Gifts, inheritances, injury awards, heirlooms, business assets not used by the family'),
            ('Unequal split', 'Only if equal would be grossly unjust or unconscionable'),
            ('Common-law', 'No automatic property rights'),
            ('Deadline', 'Within two years of the divorce'),
            ('Child support', 'Federal Child Support Guidelines (Newfoundland and Labrador table)')],
    questions=['Which assets were used for family purposes, and which are business assets?',
               'Can I trace any gift or inheritance, or was it mixed into joint accounts?',
               'Was the house owned before the marriage? (It is still shared as the matrimonial home.)',
               'Have pensions and CPP credits been valued for the years of the marriage?',
               'Is everything settled well inside the two years after the divorce?'],
    faqs=[('How is property divided in a Newfoundland and Labrador divorce?', 'Matrimonial assets are presumed to be split equally regardless of whose name they are in. A court can order otherwise only if equal division would be grossly unjust or unconscionable.'),
          ('Is the matrimonial home shared if one spouse owned it before marriage?', 'Yes. Each spouse holds a 50% interest in the matrimonial home regardless of title, whether it was bought before or during the marriage.'),
          ('Are business assets divided?', 'Business assets that were not used for family purposes are typically excluded, along with gifts, inheritances and personal injury awards.'),
          ('Do common-law partners have property rights?', 'Not under the Family Law Act, which applies to married spouses. Common-law partners may have claims such as unjust enrichment, or can opt in through a cohabitation agreement.'),
          ('Is spousal support taxable in Canada?', 'Yes. Periodic spousal support paid under a written agreement or court order is taxable to the recipient and deductible for the payer. Lump-sum support is neither, and child support is never taxable or deductible.')],
    disclaimer=disclaimer('Newfoundland and Labrador', "Newfoundland and Labrador's Family Law Act and the federal Divorce Act"),
))

# ───────────────────────── PRINCE EDWARD ISLAND ─────────────────────────
GUIDES.append(dict(
    slug='prince-edward-island', name='Prince Edward Island',
    possessive="Prince Edward Island's",
    verified='facts checked vs Prince Edward Island Family Law Act (RSPEI 1988 c. F-2.1: equalization of net family property, matrimonial home full value, excluded gifts/inheritances/injury awards/insurance, unconscionability test, married spouses only), federal Divorce Act, SSAG, Federal Child Support Guidelines; Oct 2026',
    desc='How money works in a Prince Edward Island separation or divorce: equalization of net family property under the Family Law Act, the matrimonial home rule, exclusions, common-law couples, support and the Canadian tax treatment.',
    about=['Prince Edward Island divorce', 'net family property', 'equalization', 'spousal support', 'Family Law Act'],
    lede='Prince Edward Island shares the growth in what each of you is worth during the marriage, and the family home in full even if one of you owned it first. Common-law couples are not covered. Here is how PEI handles the money, in plain language.',
    reviewed="Reviewed against Prince Edward Island's Family Law Act and the federal Divorce Act.",
    intro='A PEI separation is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how pensions are split, whether support is paid and for how long. This guide walks through how Prince Edward Island handles each of those questions.',
    short='PEI uses <strong>equalization of net family property</strong>: each spouse works out how much their net worth grew during the marriage, and the one with more pays the other <strong>half the difference</strong>. The <strong>matrimonial home</strong> counts at its full value, even if one spouse owned it first. <strong>Gifts and inheritances</strong> are excluded. The rules cover <strong>married spouses only</strong>.',
    sections=[
        ('h2', 'Two sets of rules'),
        ('p', 'A PEI divorce runs on two laws. The <strong>divorce itself and support</strong> for married spouses come under the <strong>federal Divorce Act</strong>. <strong>Property</strong> and support outside a divorce come under PEI\'s <strong>Family Law Act</strong>.'),
        ('h2', 'How PEI divides property'),
        ('p', 'Property is not split item by item. Each spouse lists what they owned on the <strong>valuation date</strong> (the day you separated with no reasonable prospect of getting back together), subtracts debts and the value of what they brought into the marriage, and arrives at their <strong>net family property</strong>. The spouse with the higher number pays the other <strong>half the difference</strong>. Property and debts acquired after separation belong to whoever acquired them.'),
        ('h3', 'The matrimonial home'),
        ('p', 'The home you lived in as a family is the big exception. Its <strong>entire value</strong> goes into the calculation, even if one spouse owned it before the marriage, so that spouse cannot deduct what it was worth on the wedding day. Either spouse can ask the court for exclusive possession.'),
        ('h3', 'What is excluded'),
        ('p', '<strong>Gifts and inheritances</strong> from someone else, <strong>personal injury awards</strong> and <strong>life insurance proceeds</strong> are excluded, as long as you can trace them. Mixing them into the family home or a joint account can lose the exclusion, and the spouse claiming it must prove it.'),
        ('callout', 'When it is not 50/50', 'A court can change the equalization amount only if it would be <strong>unconscionable</strong>, a very high bar. Examples include debts that were hidden, reckless spending of assets, or a large amount after living together for less than five years.'),
        ('h3', 'Common-law couples'),
        ('p', 'The property rules apply to <strong>married spouses</strong>. Common-law partners keep what is in their own name unless they prove a claim such as unjust enrichment or have a cohabitation agreement.'),
        ('h3', 'The house and the pensions'),
        house_pensions(),
        ('h2', 'Spousal support'),
        ('p', 'Married spouses claim spousal support under the <strong>Divorce Act</strong>; others who qualify under PEI\'s <strong>Family Law Act</strong>. Courts rely on the <strong>Spousal Support Advisory Guidelines (SSAG)</strong>: advisory, not binding, but the practical starting point.'),
        ('callout',) + TAX,
    ] + child_support('Prince Edward Island table', 'The Maintenance Enforcement Program can collect payments.') + timeline('Prince Edward Island'),
    glance=[('Property division', 'Equalization of net family property: half the difference (Family Law Act)'),
            ('Matrimonial home', 'Full value counts, even if owned before marriage'),
            ('Excluded', 'Gifts, inheritances, injury awards, life insurance, if traceable'),
            ('Valuation date', 'Separation with no reasonable prospect of reconciling'),
            ('Unequal split', 'Only if equalization would be unconscionable'),
            ('Common-law', 'No automatic property rights'),
            ('Child support', 'Federal Child Support Guidelines (Prince Edward Island table)')],
    questions=['What was each of us worth on the wedding day and on the separation date?',
               'Is any gift or inheritance traceable, or did it go into the home or joint accounts?',
               'Was the matrimonial home owned before marriage? (Its full value still counts.)',
               'Have pensions and CPP credits been valued and included on both sides?',
               'What does the SSAG range suggest for support, and how does tax change its real value?'],
    faqs=[('How is property divided in a PEI divorce?', 'Through equalization of net family property. Each spouse calculates the growth in their net worth during the marriage, and the spouse with the higher figure pays the other half the difference.'),
          ('Is the matrimonial home shared if one spouse owned it before marriage?', 'Yes. The full value of the matrimonial home is included, so the spouse who owned it before the marriage cannot deduct its wedding-day value.'),
          ('Are gifts and inheritances shared in PEI?', 'They are excluded if they can be traced, along with personal injury awards and life insurance proceeds. Putting them into the matrimonial home or joint accounts can lose the exclusion.'),
          ('Do common-law partners have property rights in PEI?', 'Not under the Family Law Act, which applies to married spouses. Common-law partners may have claims such as unjust enrichment.'),
          ('Is spousal support taxable in Canada?', 'Yes. Periodic spousal support paid under a written agreement or court order is taxable to the recipient and deductible for the payer. Lump-sum support is neither, and child support is never taxable or deductible.')],
    disclaimer=disclaimer('Prince Edward Island', "Prince Edward Island's Family Law Act and the federal Divorce Act"),
))

# ───────────────────────── QUEBEC ─────────────────────────
GUIDES.append(dict(
    slug='quebec', name='Quebec',
    verified='facts checked vs Civil Code of Quebec (family patrimony: residences, furniture, vehicles, retirement savings accumulated during marriage, QPP; gifts and inheritances excluded; partnership of acquests default regime), Educaloi (family patrimony, parental union for children born or adopted from June 30, 2025), federal Divorce Act, Quebec child support model; Oct 2026',
    desc='How money works in a Quebec separation or divorce: the family patrimony, the matrimonial regime, the new parental union for unmarried parents, Quebec\'s own child support model, spousal support and the tax treatment.',
    about=['Quebec divorce', 'family patrimony', 'parental union', 'partnership of acquests', 'Quebec child support'],
    lede='Quebec is different from the rest of Canada. Married couples share a family patrimony they cannot opt out of, child support uses Quebec\'s own model, and since 2025 unmarried parents have a new parental union regime. Here is how Quebec handles the money, in plain language.',
    reviewed='Reviewed against the Civil Code of Québec and the federal Divorce Act.',
    intro='A Quebec separation is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how retirement savings are split, whether support is paid and for how long. Quebec uses civil law, so the rules work differently from the other provinces. This guide walks through each of them.',
    short='Married and civil union spouses share a <strong>family patrimony</strong>: the family residences, furniture, vehicles, and <strong>retirement savings built up during the marriage</strong>, divided <strong>equally</strong>. Everything else depends on your <strong>matrimonial regime</strong>, by default the partnership of acquests. Unmarried couples do not share property, except parents in a <strong>parental union</strong> (children born or adopted from mid-2025). Child support follows <strong>Quebec\'s own model</strong>.',
    sections=[
        ('h2', 'Two sets of rules'),
        ('p', 'A Quebec divorce uses the <strong>federal Divorce Act</strong> for the divorce itself, but property is governed by the <strong>Civil Code of Québec</strong>. Couples who separate without divorcing, and civil union spouses, are governed by the Civil Code throughout.'),
        ('h2', 'The family patrimony'),
        ('p', 'From the day you marry, certain property forms the <strong>family patrimony</strong>, and its net value is usually <strong>divided equally</strong> when the marriage ends, whichever spouse owns it:'),
        ('ul', ['The family <strong>residences</strong> (home, cottage, vacation condo) or the rights to use them',
                '<strong>Furniture and household items</strong> in them',
                'The family\'s <strong>vehicles</strong>',
                '<strong>Retirement savings built up during the marriage</strong>, such as pension plans and RRSPs, and Quebec Pension Plan credits']),
        ('p', 'Gifts and inheritances are not part of it, even if the whole family uses the item. Company shares, and items used by only one spouse, are not included either. Married couples <strong>cannot sign away the family patrimony in advance</strong>.'),
        ('h2', 'The matrimonial regime'),
        ('p', 'Everything outside the family patrimony is divided according to your <strong>matrimonial regime</strong>. Unless you chose otherwise in a marriage contract before a notary, it is the <strong>partnership of acquests</strong>: what each of you earned or bought during the marriage (your acquests) is shared, while property you owned before, and gifts and inheritances, stay private. Couples who chose <strong>separation as to property</strong> keep their own property, but still share the family patrimony.'),
        ('callout', 'Unmarried couples: the parental union', 'Quebec does not give common-law couples automatic property rights or spousal support. Since mid-2025, though, couples who have a <strong>child born or adopted on or after June 30, 2025</strong> are automatically in a <strong>parental union</strong>: the family residences, furniture and family vehicles form a parental union patrimony, generally <strong>divided equally</strong>, and a partner who lost out financially while helping the other get ahead can claim a <strong>compensatory allowance</strong>. Couples whose children were born earlier can opt in before a notary or two witnesses.'),
        ('h3', 'The house and the retirement savings'),
        ('p', 'Because the home and retirement savings built up during the marriage are both in the family patrimony, the usual question is not whether to share them but how. Trading the house for retirement savings, or taking a lump sum instead of a pension division, can cost a lot if the after-tax values are not compared properly. Modeling these trade-offs before you agree is exactly what <span class="brand-italic">Your Divorce Angel</span> is built to help you see clearly.'),
        ('h2', 'Spousal support'),
        ('p', 'Married and civil union spouses can claim spousal support; unmarried partners cannot, even in a parental union. In a divorce, Quebec courts also refer to the <strong>Spousal Support Advisory Guidelines</strong>, adapted to Quebec\'s own child support rules. Courts can also award a <strong>compensatory allowance</strong> to a spouse whose work or sacrifices helped the other build wealth.'),
        ('callout',) + TAX,
        ('h2', 'Child support'),
        ('p', 'When both parents live in Quebec, child support is set with the <strong>Quebec child support determination model</strong>, not the federal tables. It combines both parents\' incomes, sets a basic contribution for the children, and splits it between the parents in proportion to income, adjusted for parenting time and expenses such as childcare and post-secondary studies. If one parent lives outside Quebec, the federal guidelines apply instead.'),
    ] + timeline('Quebec'),
    glance=[('Family patrimony', 'Residences, furniture, vehicles, retirement savings from the marriage: shared equally'),
            ('Opting out', 'Married couples cannot opt out of the family patrimony in advance'),
            ('Other property', 'Matrimonial regime: partnership of acquests unless a marriage contract says otherwise'),
            ('Gifts and inheritances', 'Not part of the family patrimony'),
            ('Unmarried couples', 'No property sharing or spousal support, except the parental union (children from June 30, 2025)'),
            ('Child support', 'Quebec child support determination model when both parents live in Quebec')],
    questions=['What is in our family patrimony, and what was it worth on the day the marriage ended?',
               'Which matrimonial regime are we in, and do we have a marriage contract?',
               'How much retirement savings did each of us build up during the marriage?',
               'If we are not married, are we in a parental union, and what does it include?',
               'Could either of us claim a compensatory allowance for sacrifices during the relationship?'],
    faqs=[('What is the family patrimony in Quebec?', 'A set of property shared equally by married and civil union spouses when the marriage ends: the family residences, furniture, family vehicles, and retirement savings built up during the marriage, including Quebec Pension Plan credits. Gifts and inheritances are excluded.'),
          ('Can married couples in Quebec opt out of the family patrimony?', 'Not in advance. The family patrimony applies from the day of the marriage whatever the matrimonial regime.'),
          ('Do common-law couples share property in Quebec?', 'Not automatically. The exception is the parental union: unmarried couples with a child born or adopted on or after June 30, 2025 share a parental union patrimony of the family residences, furniture and vehicles.'),
          ('How is child support calculated in Quebec?', 'When both parents live in Quebec, with the Quebec child support determination model, based on both parents\' incomes and parenting time. The federal tables apply only when one parent lives outside Quebec.'),
          ('Is spousal support taxable in Canada?', 'Yes. Periodic spousal support paid under a written agreement or court order is taxable to the recipient and deductible for the payer. Lump-sum support is neither, and child support is never taxable or deductible.')],
    disclaimer=disclaimer('Quebec', 'the Civil Code of Québec and the federal Divorce Act'),
))

# ───────────────────────── YUKON ─────────────────────────
GUIDES.append(dict(
    slug='yukon', name='Yukon',
    verified='facts checked vs Yukon Family Property and Support Act (family assets equal shares s.5, unequal division s.13, non-family assets s.14), federal Divorce Act, SSAG, Federal Child Support Guidelines; Oct 2026',
    desc='How money works in a Yukon separation or divorce: equal shares of family assets under the Family Property and Support Act, non-family and business assets, common-law partners, support and the Canadian tax treatment.',
    about=['Yukon divorce', 'family assets', 'spousal support', 'child support', 'Family Property and Support Act'],
    lede='Yukon gives each spouse an equal share of the family assets, the things you used as a family, while other assets usually stay with their owner. Common-law partners can claim support but not an automatic property split. Here is how Yukon handles the money, in plain language.',
    reviewed="Reviewed against Yukon's Family Property and Support Act and the federal Divorce Act.",
    intro='A Yukon separation is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how pensions are split, whether support is paid and for how long. This guide walks through how Yukon handles each of those questions.',
    short='Under the Family Property and Support Act, each spouse gets an <strong>equal share of family assets</strong>: property ordinarily used by the family, such as the home, vehicles, savings and pensions. <strong>Non-family assets</strong>, including many business assets, usually stay with their owner. The court can split unequally where equal would be <strong>inequitable</strong>. <strong>Common-law partners</strong> can claim support but have no automatic property rights.',
    sections=[
        ('h2', 'Two sets of rules'),
        ('p', 'A Yukon divorce runs on two laws. The <strong>divorce itself and support</strong> for married spouses come under the <strong>federal Divorce Act</strong>. <strong>Property</strong>, and support for unmarried partners, come under Yukon\'s <strong>Family Property and Support Act</strong>.'),
        ('h2', 'How Yukon divides property'),
        ('p', 'Yukon draws a line between <strong>family assets</strong> and everything else. Family assets are property ordinarily used or enjoyed by the family: the home, vehicles, household goods, bank and investment accounts, RRSPs and pensions. Each spouse is entitled to an <strong>equal share</strong> of them, whoever\'s name they are in.'),
        ('h3', 'Non-family assets'),
        ('p', 'Other property, such as a business that was not run for the family\'s benefit or investments kept apart, generally <strong>stays with the spouse who owns it</strong>. A business can still be treated as a family asset if the other spouse contributed to it, directly or by carrying more of the home and children. Gifts and inheritances from others are usually excluded if they were not mixed into family property.'),
        ('h3', 'When it is not 50/50'),
        ('p', 'The Supreme Court of Yukon can order an <strong>unequal division</strong> where equal shares would be inequitable, looking at the length of the marriage, when assets were acquired, gifts and inheritances, each spouse\'s contributions, debts and tax consequences. Assets one spouse gave away or wasted can be counted against them.'),
        ('callout', 'Common-law partners', 'Yukon\'s property rules apply to married spouses. Common-law partners keep what is in their own names unless they can prove a claim such as unjust enrichment, but they <strong>can claim spousal support</strong> under the Family Property and Support Act.'),
        ('h3', 'The house and the pensions'),
        house_pensions(),
        ('h2', 'Spousal support'),
        ('p', 'Married spouses claim spousal support under the <strong>Divorce Act</strong>, and common-law partners under the <strong>Family Property and Support Act</strong>. Courts rely on the <strong>Spousal Support Advisory Guidelines (SSAG)</strong>: advisory, not binding, but the practical starting point.'),
        ('callout',) + TAX,
    ] + child_support('Yukon table', 'The Maintenance Enforcement Program can collect payments.') + timeline('Yukon'),
    glance=[('Property division', 'Equal shares of family assets (Family Property and Support Act)'),
            ('Non-family assets', 'Usually stay with the owner, including many business assets'),
            ('Unequal split', 'Where equal shares would be inequitable'),
            ('Common-law', 'Can claim support; no automatic property split'),
            ('Spousal support', 'SSAG (advisory)'),
            ('Child support', 'Federal Child Support Guidelines (Yukon table)')],
    questions=['Which of our assets were used by the family, and which were kept separate?',
               'Did either of us contribute to the other\'s business, directly or at home?',
               'Can I trace any gift or inheritance, or was it mixed into family property?',
               'Have pensions and CPP credits been valued and included on both sides?',
               'What does the SSAG range suggest for support, and how does tax change its real value?'],
    faqs=[('How is property divided in a Yukon divorce?', 'Each spouse is entitled to an equal share of family assets, the property ordinarily used or enjoyed by the family. Non-family assets generally stay with their owner, and the court can divide unequally where equal shares would be inequitable.'),
          ('Is a business divided in Yukon?', 'A business that was not used for family purposes is usually a non-family asset that stays with its owner, unless the other spouse contributed to it.'),
          ('Do common-law partners have rights in Yukon?', 'They can claim spousal support under the Family Property and Support Act, but do not get an automatic division of property.'),
          ('Are gifts and inheritances shared in Yukon?', 'Usually not, if they were kept separate and not mixed into family property.'),
          ('Is spousal support taxable in Canada?', 'Yes. Periodic spousal support paid under a written agreement or court order is taxable to the recipient and deductible for the payer. Lump-sum support is neither, and child support is never taxable or deductible.')],
    disclaimer=disclaimer('Yukon', "Yukon's Family Property and Support Act and the federal Divorce Act"),
))

# ───────────────────────── NORTHWEST TERRITORIES and NUNAVUT ─────────────────────────
def territory(slug, name, act, verified, pn=None):
    pn = pn or name   # name as used in a sentence ('the Northwest Territories')
    PN = pn[0].upper() + pn[1:]
    return dict(
        slug=slug, name=name, title_name=pn, possessive=pn + "'s",
        verified=verified,
        desc='How money works in a separation or divorce in %s: equalization of net family property under the Family Law Act, the family home, common-law spouses, support and the Canadian tax treatment.' % pn,
        about=['%s divorce' % name, 'net family property', 'equalization', 'spousal support', 'Family Law Act'],
        lede='%s shares the growth in what each of you is worth during the relationship, and treats couples who lived together for two years, or less with a child, much like married spouses. Here is how %s handles the money, in plain language.' % (PN, pn),
        reviewed="Reviewed against the %s and the federal Divorce Act." % act,
        intro='A separation in %s is, at its heart, a financial event. Most of the decisions that shape your next ten years are about money: who keeps the house, how pensions are split, whether support is paid and for how long. This guide walks through how %s handles each of those questions.' % (pn, pn),
        short='%s uses <strong>equalization of net family property</strong>: each spouse works out the growth in their net worth during the relationship, and the one with more pays the other <strong>half the difference</strong>. The <strong>family home</strong> gets special treatment. <strong>Common-law spouses</strong> who lived together two years, or in a lasting relationship with a child, are covered too. Courts depart from 50/50 only when it would be <strong>unconscionable</strong>.' % PN,
        sections=[
            ('h2', 'Two sets of rules'),
            ('p', 'A divorce in %s runs on two laws. The <strong>divorce itself and support</strong> for married spouses come under the <strong>federal Divorce Act</strong>. <strong>Property</strong>, and support for unmarried spouses, come under the territory\'s <strong>Family Law Act</strong>.' % pn),
            ('h2', 'How %s divides property' % PN),
            ('p', 'Property is not split item by item. Each spouse adds up what they own at separation, subtracts debts and the value of what they brought into the relationship, and arrives at their <strong>net family property</strong>, essentially the growth in their net worth. The spouse with the higher figure pays the other <strong>half the difference</strong>. A negative figure counts as zero.'),
            ('h3', 'The family home'),
            ('p', 'The family home is treated differently from other property: its value is generally shared rather than deducted as something one spouse brought in. A court can also give one spouse <strong>exclusive possession</strong> of the home for a time, for example so the children can stay.'),
            ('h3', 'When it is not 50/50'),
            ('p', 'A court can change the equalization amount only if an equal split would be <strong>unconscionable</strong>, for example reckless debts, deliberately wasting property, or hiding debts from before the relationship.'),
            ('callout', 'Common-law spouses are included', 'The Family Law Act treats a couple as spouses after <strong>two years of living together</strong>, or a relationship of some permanence with a <strong>child</strong>. That brings the same property and support rules as marriage, so a cohabitation agreement matters if you want something different.'),
            ('h3', 'The house and the pensions'),
            house_pensions(),
            ('h2', 'Spousal support'),
            ('p', 'Married spouses claim spousal support under the <strong>Divorce Act</strong>, and common-law spouses under the territory\'s <strong>Family Law Act</strong>. Courts rely on the <strong>Spousal Support Advisory Guidelines (SSAG)</strong>: advisory, not binding, but the practical starting point.'),
            ('callout',) + TAX,
        ] + child_support('%s table' % name, 'The Maintenance Enforcement Program can collect payments.') + timeline(pn),
        glance=[('Property division', 'Equalization of net family property: half the difference (Family Law Act)'),
                ('Family home', 'Special treatment; exclusive possession can be ordered'),
                ('Who is a spouse', 'Married, or 2 years living together, or a lasting relationship with a child'),
                ('Unequal split', 'Only if equalization would be unconscionable'),
                ('Spousal support', 'SSAG (advisory)'),
                ('Child support', 'Federal Child Support Guidelines (%s table)' % name)],
        questions=['What was each of us worth when the relationship began, and at separation?',
                   'Do we count as spouses under the Family Law Act if we were not married?',
                   'How is the family home being treated in the calculation?',
                   'Have pensions and CPP credits been valued and included on both sides?',
                   'What does the SSAG range suggest for support, and how does tax change its real value?'],
        faqs=[('How is property divided in a divorce in %s?' % pn, 'Through equalization of net family property. Each spouse calculates the growth in their net worth during the relationship, and the spouse with the higher figure pays the other half the difference.'),
              ('Do common-law couples share property in %s?' % pn, 'Yes, if they qualify as spouses under the Family Law Act: generally two years of living together, or a relationship of some permanence with a child.'),
              ('Can a court divide property unequally?', 'Only if an equal split would be unconscionable, for example because of reckless debts or deliberately wasted property.'),
              ('How is child support calculated in %s?' % pn, 'Under the Federal Child Support Guidelines, using the %s table for the paying parent\'s income and the number of children, plus a share of special expenses.' % name),
              ('Is spousal support taxable in Canada?', 'Yes. Periodic spousal support paid under a written agreement or court order is taxable to the recipient and deductible for the payer. Lump-sum support is neither, and child support is never taxable or deductible.')],
        disclaimer=disclaimer(pn, 'the %s and the federal Divorce Act' % act),
    )

GUIDES.append(territory('northwest-territories', 'Northwest Territories', "Northwest Territories' Family Law Act",
    'facts checked vs Northwest Territories Family Law Act (S.N.W.T. 1997 c.18: equalization of net family property, spouse includes 2 years cohabitation or relationship of permanence with child), federal Divorce Act, SSAG, Federal Child Support Guidelines; Oct 2026', pn='the Northwest Territories'))
GUIDES.append(territory('nunavut', 'Nunavut', "Nunavut's Family Law Act",
    'facts checked vs Nunavut Family Law Act (CSNu c. F-30: equalization of net family property modeled on Ontario, matrimonial home special treatment s.6, unconscionability, spouse includes 2 years cohabitation or permanence with child), federal Divorce Act, SSAG, Federal Child Support Guidelines; Oct 2026'))
